const RIGHT_ARROW = 39;
const LEFT_ARROW = 37;
const DOWN_ARROW = 40;
const A_KEYCODE = 65;
const S_KEYCODE = 83;
const D_KEYCODE = 68;

const MAX_SCORE = 3;

const PLAYER_ONE = 'playerOne';
const PLAYER_TWO = 'playerTwo';

const INITIAL_ROW_NUMBER = 8;
const INITIAL_COL_NUMBER = 8;
const INITIAL_WINCOUNT_NUMBER = 4;

const MIN_VALID_NAME_LENGTH = 3;
const MIN_VALID_ROW_COL_NUMBER = 4;
const MIN_VALID_WINCOUNT_NUMBER = 2;


export {
    RIGHT_ARROW, LEFT_ARROW, DOWN_ARROW, A_KEYCODE, S_KEYCODE, D_KEYCODE,
    MAX_SCORE,
    PLAYER_ONE, PLAYER_TWO,
    INITIAL_ROW_NUMBER, INITIAL_COL_NUMBER, INITIAL_WINCOUNT_NUMBER,
    MIN_VALID_NAME_LENGTH, MIN_VALID_ROW_COL_NUMBER, MIN_VALID_WINCOUNT_NUMBER
};
